#!/usr/bin/env bash
# script  redirecting to /redirect_me to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
