#!/usr/bin/env bash
# script  redirecting to /redirect_me to another page
apt-get -y update
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
