#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
new_string="listen 80;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
new_string2="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$new_string2/" /etc/nginx/nginx.conf
sudo service nginx start
