#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get  update
sudo apt-get -y install nginx

HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
sudo service nginx restart
