#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy=2.4.\*

musconfig=\

echo '
frontend mwihotidan.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 237590-web-01 52.3.254.102
        server 237590-web-02 100.26.247.157
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
