#!/usr/bin/env bash
#displays bad luck on 4th iter, good luck on 8th iter other iter Displays Best School
i=1
while [ "$i" -le 10 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
