#!/usr/bin/env bash
#displays numbers from 1-20 displays bad luck from China on 4 iter, bad luck from Japan on 9th iter, 17 display bad luck from Italy
i=1
while [ "$i" -le 20 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "4"
		echo "bad luck from China"
	elif [ "$i" -eq 9 ]
	then
		echo "9"
		echo "bad luck from Japan"
	elif [ "$i" -eq 17 ]
	then
		echo "17"
		echo "bad luck from Italy"
	else
		echo "$i"
	fi
	((i++))
done
