#!/usr/bin/env bash
#displays numbers from 1-20 displays bad luck from China on 4 iter, bad luck from Japan on 9th iter, 17 display bad luck from Italy
i=1
while [ "$i" -le 20 ]
do
	case $i in 4)
		echo "4"
		echo "bad luck from China"
		;;
	9)
		echo "9"
		echo "bad luck from Japan"
		;;
	17)
		echo "17"
		echo "bad luck from Italy"
		;;
	*)
		echo "$i"
	esac
	((i++))
done
