#!/usr/bin/env bash
#  connect to a server without typing a password.

Include /etc/ssh/ssh_config.d/*.conf

Host *
    PasswordAuthentication no
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
